---
# defaults file for core
process_state: 'up'
gts_always_up_processes:
  - 'ActiveMQ'
  - 'HostController'
  - 'Jboss'
  - 'LocalMySQL'
  - 'MonitorStateCal'
  - 'RDS-'
  - 'SCHEDULER'
  - 'SystemController'
  - 'SystemMonitor'

gts_exclude_processes:
  - 'PerformanceLogger'
  - 'NewsService'
  - 'AuditTrail-12'
  - 'AuditTrail-212'

retries: 15
