---
proxy_setting:
  HTTP_PROXY: http://proxy2.inf.ise.com:3128
  HTTPS_PROXY: http://proxy2.inf.ise.com:3128
  http_proxy: http://proxy2.inf.ise.com:3128
  https_proxy: http://proxy2.inf.ise.com:3128
  proxy: http://proxy2.inf.ise.com:3128

oat_env: 038
gtsstatus: echo 'echo "gtsstatus" | opcon -s' | gtsenv
gtsstatus_m: echo 'echo "gtsstatus -m" | opcon -s' | gtsenv